### ISSUE TITLE
StyleInjector changes prevents build with current gwt release (1.7.0)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Neseek77/google-web-toolkit-incubator#306]
```
What version of gwt and gwt-incubator are you using?
gwt:
com.google.gwt.eclipse.sdkbundle.linux_1.7.0.v200907291526/gwt-linux-1.7.0
gwt-incubator:
trunk

What OS and browser are you using?
linux/firefox 3.0.14
Do you see this error in hosted mode, web mode, or both?
 na
(If possible, please include a test case that shows the problem)

The wiki documentation advises that you build the incubator trunk
with the most recent -release- version of gwt.  A recent change to the
incubator trunk seems to be inconsistent and builds fail against the
current gwt release for the following files related to StyleInjector.  With
build errors like:
[gwt.javac]
/home/bhills/src/incubator/src/com/google/gwt/widgetideas/client/FastTree.java:1
9:
cannot find symbol
[gwt.javac] symbol  : class StyleInjector
[gwt.javac] location: package com.google.gwt.dom.client
[gwt.javac] import com.google.gwt.dom.client.StyleInjector;


bhills@brent-desktop:~/src/incubator$ svn log
com/google/gwt/widgetideas/client/ValueSpinner.java
------------------------------------------------------------------------
r1712 | rjrjr@google.com | 2009-09-09 12:37:00 -0700 (Wed, 09 Sep 2009) | 2
lines

Delete incubator StyleInjector, and use the one in GWT instead


Applies to:
com/google/gwt/widgetideas/client/ValueSpinner.java
com/google/gwt/gen2/widgetbase/client/Gen2CssInjector.java
com/google/gwt/widgetideas/client/CurrencyWidgetWithPreview.java
com/google/gwt/widgetideas/client/FastTree.java:133: cannot find symbol

Hopefully using the test case you have generously provided, what steps will
reproduce the problem? 
1.build trunk against current gwt release fails
2.
3.

What is the expected output? What do you see instead?

Workaround if you have one:

I suspect (but have yet to test) that the build for incubator requires use
of the GWT source instead of the current released version.  If so it should
be documented that way.

Please provide any additional information below,  and thank you for taking
the time and effort to report this issue, as good issue reports are
critical for our quest to make GWT's new widgets and libraries shine.

```

Original issue reported on code.google.com by `hillsbr...@gmail.com` on 12 Sep 2009 at 3:52
